version: '3.7'

services:
  app-server:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "8090:8090" 
    restart: always  
    networks: 
      - backend
      - frontend

  app-client:
    build:
      context: frontend 
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://127.0.0.1:8090
    ports:
      - "8000:80" 
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend  

networks:
  backend:
  frontend:    